#!/usr/bin/env bash
# Extracts the algo namespace from main.cpp into a standalone header.
#
# main.cpp defines main(), so tests cannot include it directly. Rather than keeping a second
# copy of the library that would drift, they include the header this script produces. main.cpp
# stays the single source of truth.
#
# Usage:
#   scripts/extract_library.sh <output-header>

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ $# -ne 1 ]]; then
  echo "usage: scripts/extract_library.sh <output-header>" >&2
  exit 1
fi

output="$1"

opening="namespace algo {"
closing="}  // namespace algo"

count_lines() {
  grep -c -x -F "$1" main.cpp || true
}

if [[ "$(count_lines "$opening")" != "1" || "$(count_lines "$closing")" != "1" ]]; then
  echo "error: main.cpp must contain exactly one '$opening' line and one '$closing' line" >&2
  exit 1
fi

mkdir -p "$(dirname "$output")"

{
  echo "// Generated by scripts/extract_library.sh from main.cpp. Do not edit."
  echo "#pragma once"
  echo "#include <bits/stdc++.h>"
  echo
  sed -n "/^$(printf '%s' "$opening" | sed 's/[][\.*^$/]/\\&/g')\$/,/^$(printf '%s' "$closing" | sed 's/[][\.*^$/]/\\&/g')\$/p" main.cpp
  echo
  echo "namespace ds = algo::data_structures;"
  echo "namespace gr = algo::graphs;"
} > "$output"

echo "wrote $output"
